### ISSUE TITLE
Add setting for different WC3 location

### ISSUE THREAD

**Issue by tomaskallup** [uakfdotb/wc3connect-java#2]
I'm on Mac and I get the warning that my game couldn't be detected. I installed it in my Applications folder and I would like to keep it there, as then I have all apps/games in one place. Could you please add a setting to change the path where wc3connect look for the game?

**Comment by uakfdotb** [comment]
Sorry for the slow response. I don't plan to add that, but you can ignore the warning and just start Warcraft III separately. The detection is just to make it easier for players who might not know how to backup their 1.30.1 installation (in case they want to have one installation upgraded to latest patch for playing on Battle.net, and one for playing with WC3Connect).

**Comment by uakfdotb** [comment]
Sorry for the slow response. I don't plan to add that, but you can ignore the warning and just start Warcraft III separately. The detection is just to make it easier for players who might not know how to backup their 1.30.1 installation (in case they want to have one installation upgraded to latest patch for playing on Battle.net, and one for playing with WC3Connect).
