### ISSUE TITLE
No Password Encryption

### ISSUE THREAD

**Issue by XXXandBEER** [uakfdotb/wc3connect-java#4]
In both the login and signup API our usernames/passwords are simply converted from plain text to binary and sent over the network. That's not secure at all and makes the door wide open for brute forcing/packet sniffing/etc.

Please encrypt user PI before sending it over a network. Binary does not count as encrypting user data...

**Comment by uakfdotb** [comment]
The username/password are sent over HTTPS connection. This is same as what happens when you login to Facebook, Google, etc. If you don't think it is secure then start by notifying those companies.

**Comment by uakfdotb** [comment]
Packet sniffing cannot decrypt SSL. Unless certificate is compromised and forward secrecy disabled. SSL is handled by Java standard library so that is why you don't see the encryption in this codebase. It is not smart to roll out our own cryptography library.

**Comment by XXXandBEER** [comment]
The companies you mentioned use 2FA, OAUTH 2.0, and API Keys they don't encrypt user PI to binary as part of the API. I'm specifically talking about your request to `https://connect.entgaming.net/gwc-login` the post request data is literally `username:password` show me a company that allows that and doesn't consider it insecure.

**Comment by uakfdotb** [comment]
It is encrypted with SSL (HTTPS) (industry standard).
